---

- name: Clone the git repo for bench
  git:
    accept_hostkey: yes
    repo: '{{ frappe_repo }}'
    dest: '{{ frappe_repo_path }}'
  register: frappe_bench_repo_status
  become: yes
  become_user: '{{ frappe_user }}'

- name: Pip install bench
  pip:
    chdir: '{{ frappe_repo_path|dirname }}'
    extra_args: --user -e
    name: .bench
  when: frappe_bench_repo_status.changed
  become: yes
  become_user: '{{ frappe_user }}'
  changed_when: False

- name: Create a new bench
  shell: bench init {{ frappe_path|basename }}
  environment: '{{ frappe_env }}'
  args:
    chdir: '{{ frappe_path|dirname }}'
    creates: '{{ frappe_path }}/package.json'
    executable: '/bin/bash'
  become: yes
  become_user: '{{ frappe_user }}'

- name: Add a site
  shell: bench new-site --db-name {{ frappe_user }} --mariadb-root-password {{ frappe_mysql_password }} --admin-password {{ frappe_admin_password }} {{ frappe_site }}
  register: bench_site_status
  environment: '{{ frappe_env }}'
  args:
    chdir: '{{ frappe_path }}'
    creates: '{{ frappe_path }}/sites/{{ frappe_site }}/site_config.json'
    executable: '/bin/bash'
  become: yes
  become_user: '{{ frappe_user }}'

- name: Add apps
  shell: bench get-app erpnext https://github.com/frappe/{{ item }}
  environment: '{{ frappe_env }}'
  args:
    chdir: '{{ frappe_path }}'
    creates: '{{ frappe_path }}/apps/{{ item }}/README.md'
    executable: '/bin/bash'
  with_items: '{{ frappe_apps }}'
  become: yes
  become_user: '{{ frappe_user }}'

- name: List and register apps
  shell: bench --site {{ frappe_site }} list-apps
  changed_when: False
  register: apps_list
  environment: '{{ frappe_env }}'
  args:
    chdir: '{{ frappe_path }}'
    executable: '/bin/bash'
  become: yes
  become_user: '{{ frappe_user }}'

- name: Install apps
  shell: bench --site {{ frappe_site }} install-app {{ item }}
  when: item not in apps_list.stdout
  environment: '{{ frappe_env }}'
  with_items: '{{ frappe_apps }}'
  args:
    chdir: '{{ frappe_path }}'
    executable: '/bin/bash'
  become: yes
  become_user: '{{ frappe_user }}'

- name: Synchronize
  shell: bench {{ item }}
  environment: '{{ frappe_env }}'
  args:
    chdir: '{{ frappe_path }}'
    executable: '/bin/bash'
  when: bench_site_status.changed
  with_items:
    - migrate
    - build
  become: yes
  become_user: '{{ frappe_user }}'

- name: Supervisor if is not configured
  shell: bench setup supervisor
  environment: '{{ frappe_env }}'
  args:
    chdir: '{{ frappe_path }}'
    creates: '{{ frappe_path }}/config/supervisor.conf'
    executable: '/bin/bash'
  become: yes
  become_user: '{{ frappe_user }}'

- name: Link supervisor.conf
  file:
    src: '{{ frappe_path }}/config/supervisor.conf'
    dest: /etc/supervisor/conf.d/frappe-bench.conf
    state: link

- name: Restart supervisor service
  systemd: name=supervisor state=restarted
  changed_when: False
