---

- name: Clone the git repo for bench
  git:
    accept_hostkey: yes
    repo: '{{ erpnext_repo }}'
    dest: '{{ erpnext_path }}/bench-repo'
  register: frappe_bench_repo_status
  become: yes
  become_user: '{{ erpnext_user }}'

- name: Pip install bench
  pip:
    chdir: '{{ erpnext_path }}'
    extra_args: --user -e
    name: bench-repo
  when: frappe_bench_repo_status.changed
  become: yes
  become_user: '{{ erpnext_user }}'
  changed_when: False

- name: Create a new bench
  shell: bench init frappe-bench
  register: init_res
  environment: '{{ frappe_env }}'
  args:
    chdir: '{{ erpnext_path }}'
    creates: '{{ erpnext_path }}/frappe-bench/package.json'
    executable: '/bin/bash'
  become: yes
  become_user: '{{ erpnext_user }}'

- debug: var=init_res

- name: Add a site
  shell: bench new-site --db-name {{ erpnext_user }} --mariadb-root-password {{ erpnext_mysql_root_pass }} --admin-password {{ erpnext_user }} {{ erpnext_site }}
  register: bench_site_status
  environment: '{{ frappe_env }}'
  args:
    chdir: '{{ erpnext_path }}/frappe-bench'
    creates: '{{ erpnext_path }}/frappe-bench/sites/{{ erpnext_site }}/site_config.json'
    executable: '/bin/bash'
  become: yes
  become_user: '{{ erpnext_user }}'

- debug: var=bench_site_status

- name: Add apps
  shell: bench get-app erpnext https://github.com/frappe/{{ item }}
  register: addapp_res
  environment: '{{ frappe_env }}'
  args:
    chdir: '{{ erpnext_path }}/frappe-bench'
    creates: '{{ erpnext_path }}/frappe-bench/apps/{{ item }}/README.md'
    executable: '/bin/bash'
  with_items: '{{ erpnext_apps }}'
  become: yes
  become_user: '{{ erpnext_user }}'

- debug: var=addapp_res

- name: List and register apps
  shell: bench --site {{ erpnext_site }} list-apps
  changed_when: False
  register: apps_list
  environment: '{{ frappe_env }}'
  args:
    chdir: '{{ erpnext_path }}/frappe-bench'
    executable: '/bin/bash'
  become: yes
  become_user: '{{ erpnext_user }}'

- debug: var=apps_list

- name: Install apps
  shell: bench --site {{ erpnext_site }} install-app {{ item }}
  when: item not in apps_list.stdout
  environment: '{{ frappe_env }}'
  with_items: '{{ erpnext_apps }}'
  args:
    chdir: '{{ erpnext_path }}/frappe-bench'
    executable: '/bin/bash'
  become: yes
  become_user: '{{ erpnext_user }}'

- name: Synchronize
  shell: bench {{ item }}
  environment: '{{ frappe_env }}'
  args:
    chdir: '{{ erpnext_path }}/frappe-bench'
    executable: '/bin/bash'
  when: bench_site_status.changed
  with_items:
    - migrate
    - build
  become: yes
  become_user: '{{ erpnext_user }}'

- name: Supervisor if not configured
  shell: bench setup supervisor
  args:
    chdir: '{{ erpnext_path }}/frappe-bench'
    creates: '{{ erpnext_path }}/frappe-bench/config/supervisor.conf'
    executable: '/bin/bash'
  become: yes
  become_user: '{{ erpnext_user }}'

- name: Link supervisor.conf
  file:
    src: '{{ erpnext_path }}/frappe-bench/config/supervisor.conf'
    dest: /etc/supervisor/conf.d/frappe-bench.conf
    state: link
  register: supervisor_link

- name: Restart supervisor service
  systemd: name=supervisor state=restarted
  changed_when: False
