---

- name: Clone the git repo for bench
  git:
    accept_hostkey: yes
    repo: '{{ erpnext_repo }}'
    dest: '{{ erpnext_path }}/bench-repo'
  become: yes
  become_user: '{{ erpnext_user }}'

- name: Pip install bench
  pip:
    chdir: '{{ erpnext_path }}'
    extra_args: --user -e
    name: bench-repo
  become: yes
  become_user: '{{ erpnext_user }}'

- name: Create a new bench
  command: ~/.local/bin/bench init frappe-bench
  args:
    chdir: '{{ erpnext_path }}'
    creates: '{{ erpnext_path }}/frappe-bench/package.json'
  become: yes
  become_user: '{{ erpnext_user }}'
