---

- name: Create erpnext user
  user:
    name: '{{ erpnext_user }}'

- name: Install system packages
  apt:
    pkg: '{{ item }}'
    update_cache: yes
  with_items:
    - acl
    - git
    - python-setuptools
    - python-dev
    - python-pip
    - virtualenv
    - libpq-dev
    - libsasl2-dev
    - libldap2-dev
    - libffi-dev
    - libssl-dev
    - openssl
    - build-essential
    - libxrender-dev
    - libx11-dev
    - libfontconfig1-dev
    - libfreetype6-dev
    - fontconfig
    - nodejs
    - npm

# - name: Install n
#   become: True
#   become_user: '{{ erpnext_user }}'
#   shell: curl -L https://git.io/n-install | bash -s -- -y latest
#   args:
#     creates: /home/{{ erpnext_user }}/n/bin/n
#     executable: /bin/bash
- name: Install node n
  npm:
    name: n
    global: yes

- name: Install node
  shell: n latest
