---

- name: Create frappe user
  user:
    name: '{{ frappe_user }}'

- name: Install system packages
  apt:
    pkg: '{{ item }}'
    update_cache: yes
  with_items:
    - acl
    - git
    - python-setuptools
    - python-dev
    - python-pip
    - virtualenv
    - libpq-dev
    - libsasl2-dev
    - libldap2-dev
    - libffi-dev
    - libssl-dev
    - openssl
    - build-essential
    - libxrender-dev
    - libx11-dev
    - libfontconfig1-dev
    - libfreetype6-dev
    - libxext-dev
    - fontconfig
    - supervisor

- name: Install n
  become_user: '{{ frappe_user }}'
  shell: curl -L https://git.io/n-install | SHELL=/bin/bash bash -s -- -y stable
  args:
    creates: '{{ _frappe_home }}/n/bin/n'
    executable: /bin/bash
