---

- include_role: name=plumelo.mysql private=true
  vars:
    mysql_root_pass: '{{ frappe_mysql_password }}'
    mysql_package: mariadb
    mysql_users:
      - name: 'root'
        append_privs: yes
        state: present
        pass: '{{ frappe_mysql_password }}'
        privs:
          - "*.*:ALL,GRANT"
        hosts:
          - localhost
          - 127.0.0.1
    mysql_config:
      mysqld:
        innodb_file_format: barracuda
        innodb_file_per_table: 1
        innodb_large_prefix: 1
        character_set_client_handshake: 'FALSE'
        character_set_server: utf8mb4
        collation_server: utf8mb4_unicode_ci
      mysql:
        default_character_set: utf8mb4

- name: Allow root login on localhost
  command: 'mysql -ne "{{item}}"'
  with_items:
    - GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost' IDENTIFIED BY '{{ frappe_mysql_password }}' WITH GRANT OPTION
    - FLUSH PRIVILEGES
  changed_when: False
