---

- include_role: name=jdauphant.nginx private=true
  vars:
    nginx_official_repo: True
    nginx_official_repo_mainline: True
    nginx_sites:
      default:
        template: 'frappe.conf.j2'
        server_name: '_'
